## GradientDescent

In [35]:
import numpy as np
import pandas as pd
df= pd.read_csv("C:\\Program Files\\Python36\\suven\\Notebooks\\test_scores.csv",sep=",")
print(df)
x_reprentation=["math"]
y_reprentation=["cs"]
print(x_reprentation)
print(y_reprentation)
array_x=df['math']
x = np.array(array_x)
i, = np.where(x == 70)
print(x)
print("Value of Index",i)
print(x.shape)
array_y=df['cs']
y=np.array(array_y)
print(y)
z=np.array([array_x,array_y])
print(z)
i,j = np.where(z == 80)
print(i,j)
print(z.shape)
print(z[1][3])

     name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73
['math']
['cs']
[92 56 88 70 80 49 65 35 66 67]
Value of Index [3]
(10,)
[98 68 81 80 83 52 66 30 68 73]
[[92 56 88 70 80 49 65 35 66 67]
 [98 68 81 80 83 52 66 30 68 73]]
[0 1] [4 3]
(2, 10)
80
