## Load NumPy

In [59]:
import numpy as np
import sys

## The Basics

In [60]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [61]:
b=np.array([[3.2,4.5,3.8],[3.6,5.8,5.9]])
print(b)

[[3.2 4.5 3.8]
 [3.6 5.8 5.9]]


In [62]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [63]:
#Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [64]:
#Get Type
a.dtype

dtype('int32')

In [65]:
#Get Size
a.itemsize

4

In [66]:
#Get Elements Size
b.size

6

In [67]:
#Get total size
a.nbytes

12

## Accessing/Changing specific elements,rows or columns etc.

In [68]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [69]:
#Get Shape
a.shape

(2, 7)

In [70]:
#Get Specific Element [r,c]
a[1][5]

13

In [71]:
#Get Specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
#Get Specific row
a[:,2]

array([ 3, 10])

In [73]:
#Getting little more fancy(startindex:endindex:stepsize)
a[0,2:8:3]

array([3, 6])

In [74]:
#Replace Element
a[1][5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### 3*d element array

In [75]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [76]:
#Get specific Element(Work Outside in)
b[0,1,2]

6

In [77]:
#replace
b[1,0,:]=[13,14,15]
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [10 11 12]]]


### Initializing Different Types of Array

In [78]:
#All 0's Matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
#All 1's Matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [80]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [81]:
#Any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [82]:
#Random Decimal Number
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.08250396 0.65913176]
 [0.15038126 0.98409315]
 [0.25758931 0.51397726]
 [0.58256296 0.45975745]]
[[0.10556178 0.35326244 0.70148955 0.96960131 0.8938174  0.12198216
  0.13903699]
 [0.93223766 0.57578823 0.36804433 0.72098133 0.60941421 0.97137354
  0.02065715]]


In [83]:
#Random Integer Value
np.random.randint(7,size=(3,2))

array([[1, 3],
       [4, 2],
       [1, 2]])

In [84]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
#Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [86]:
array=np.ones((5,5))
zeros=np.zeros((3,3))
zeros[1][1]=9
array[1:4,1:4]=zeros
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [92]:
array=np.full((5,5),5)
zeros=np.zeros((3,3))
zeros[2][2]=105
array[1:4,1:4]=zeros
print(array)
print(np.full_like(array,10))

[[  5   5   5   5   5]
 [  5   0   0   0   5]
 [  5   0   0   0   5]
 [  5   0   0 105   5]
 [  5   5   5   5   5]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
